### ISSUE TITLE
Hi Zibri

### ISSUE THREAD

**Issue by xlovinglyx** [Zibri/ZiPhone#10]
How could i change 2 imei's in an iphone 11 if i have 2 sim slots & 2 imei's..
I saw a picture of the advanced way of chaning the imei in ziphone but it shows only one imei..?

& ppl say it's temporary, how would the change of imei be altered/modified again or is there a timeout ?

**Comment by Zibri** [comment]
#LOL ZiPhone is for the first iPhone. You are 14 years too late to the party :D
